// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/pulsaar.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulsaarAgent_ListDirectory_FullMethodName = "/pulsaar.v1.PulsaarAgent/ListDirectory"
	PulsaarAgent_Stat_FullMethodName          = "/pulsaar.v1.PulsaarAgent/Stat"
	PulsaarAgent_ReadFile_FullMethodName      = "/pulsaar.v1.PulsaarAgent/ReadFile"
	PulsaarAgent_StreamFile_FullMethodName    = "/pulsaar.v1.PulsaarAgent/StreamFile"
	PulsaarAgent_Health_FullMethodName        = "/pulsaar.v1.PulsaarAgent/Health"
)

// PulsaarAgentClient is the client API for PulsaarAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulsaarAgentClient interface {
	ListDirectory(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	StreamFile(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pulsaarAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewPulsaarAgentClient(cc grpc.ClientConnInterface) PulsaarAgentClient {
	return &pulsaarAgentClient{cc}
}

func (c *pulsaarAgentClient) ListDirectory(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, PulsaarAgent_ListDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulsaarAgentClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, PulsaarAgent_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulsaarAgentClient) ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, PulsaarAgent_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulsaarAgentClient) StreamFile(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulsaarAgent_ServiceDesc.Streams[0], PulsaarAgent_StreamFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, ReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulsaarAgent_StreamFileClient = grpc.ServerStreamingClient[ReadResponse]

func (c *pulsaarAgentClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PulsaarAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulsaarAgentServer is the server API for PulsaarAgent service.
// All implementations must embed UnimplementedPulsaarAgentServer
// for forward compatibility.
type PulsaarAgentServer interface {
	ListDirectory(context.Context, *ListRequest) (*ListResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ReadFile(context.Context, *ReadRequest) (*ReadResponse, error)
	StreamFile(*StreamRequest, grpc.ServerStreamingServer[ReadResponse]) error
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedPulsaarAgentServer()
}

// UnimplementedPulsaarAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulsaarAgentServer struct{}

func (UnimplementedPulsaarAgentServer) ListDirectory(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedPulsaarAgentServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedPulsaarAgentServer) ReadFile(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedPulsaarAgentServer) StreamFile(*StreamRequest, grpc.ServerStreamingServer[ReadResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamFile not implemented")
}
func (UnimplementedPulsaarAgentServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPulsaarAgentServer) mustEmbedUnimplementedPulsaarAgentServer() {}
func (UnimplementedPulsaarAgentServer) testEmbeddedByValue()                      {}

// UnsafePulsaarAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulsaarAgentServer will
// result in compilation errors.
type UnsafePulsaarAgentServer interface {
	mustEmbedUnimplementedPulsaarAgentServer()
}

func RegisterPulsaarAgentServer(s grpc.ServiceRegistrar, srv PulsaarAgentServer) {
	// If the following call panics, it indicates UnimplementedPulsaarAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulsaarAgent_ServiceDesc, srv)
}

func _PulsaarAgent_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsaarAgentServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsaarAgent_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsaarAgentServer).ListDirectory(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulsaarAgent_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsaarAgentServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsaarAgent_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsaarAgentServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulsaarAgent_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsaarAgentServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsaarAgent_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsaarAgentServer).ReadFile(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulsaarAgent_StreamFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulsaarAgentServer).StreamFile(m, &grpc.GenericServerStream[StreamRequest, ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulsaarAgent_StreamFileServer = grpc.ServerStreamingServer[ReadResponse]

func _PulsaarAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsaarAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsaarAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsaarAgentServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PulsaarAgent_ServiceDesc is the grpc.ServiceDesc for PulsaarAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulsaarAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulsaar.v1.PulsaarAgent",
	HandlerType: (*PulsaarAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDirectory",
			Handler:    _PulsaarAgent_ListDirectory_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _PulsaarAgent_Stat_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _PulsaarAgent_ReadFile_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PulsaarAgent_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFile",
			Handler:       _PulsaarAgent_StreamFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/pulsaar.proto",
}
